name: CI

on:
  push:
  schedule:
  - cron:  '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Run tests in Docker
      run: ./run_tests_in_docker
